Repository YGNI-RType/GEngine, pull requests merged in 2024-10, with the labels that each got.

#1 feat: ci
  .github/workflows/compilation-gengine.yml
Labels: enhancement

#3 update(cmake): compilation flags & windows socket
  CMakeLists.txt
Labels: enhancement

#6 Fixed beautify in CI
  .gitattributes
  .github/workflows/compilation-gengine.yml
  beautify.sh
  include/GEngine/net/cl_net_client.hpp
  include/GEngine/net/net_server.hpp
  source/GEngine/net/net.cpp
  source/GEngine/net/net_server.cpp
Labels: bug

#5 Network ecs
  .gitattributes
  .github/workflows/compilation-gengine.yml
  beautify.sh
  include/GEngine/BaseEngine.hpp
  include/GEngine/interface/network/Networked.hpp
  include/GEngine/interface/network/systems/NetworkComponent.hpp
  include/GEngine/interface/network/systems/Snapshot.hpp
  include/GEngine/interface/network/systems/Updater.hpp
  include/GEngine/net/cl_net_client.hpp
  include/GEngine/net/net_common.hpp
  include/GEngine/net/net_queue.hpp
  include/GEngine/net/net_server.hpp
  include/GEngine/net/net_socket.hpp
  include/ecs/component/Manager.hpp
  include/ecs/component/Manager.inl
  include/ecs/component/SparseArray.hpp
  include/ecs/system/Base.hpp
  include/ecs/system/Base.inl
  source/GEngine/interface/network/systems/Snapshot.cpp
  source/GEngine/interface/network/systems/Updater.cpp
  source/GEngine/libdev/systems/driver/input/KeyboardCatcher.cpp
  source/GEngine/net/net.cpp
  source/ecs/ECS.cpp
  source/ecs/component/Manager.cpp
Labels: enhancement

#16 fixed network: ack was falsified due to fragmentation
  Rtype/source/main.cpp
  Rtype/source/systems/Start.cpp
  include/GEngine/libdev/systems/events/driver/output/Sound.hpp
  include/GEngine/net/msg.hpp
  include/GEngine/net/net_channel.hpp
  source/GEngine/libdev/systems/driver/output/SoundManager.cpp
  source/GEngine/net/msg/msg_udp.cpp
  source/GEngine/net/net_channel.cpp
  source/GEngine/net/net_channel_pool.cpp
Labels: bug

#17 Feat/libdev animations
  Rtype/assets/animations/r-typesheet3.json
  Rtype/assets/animations/r-typesheet42.json
  Rtype/assets/sprites/r-typesheet42.gif
  Rtype/cmake/automate-vcpkg-gengine.cmake
  Rtype/include/components/Monster.hpp
  Rtype/include/components/Player.hpp
  Rtype/include/events/Movement.hpp
  Rtype/include/events/Shoot.hpp
  Rtype/include/systems/BackgroundMotion.hpp
  Rtype/include/systems/ClearBullets.hpp
  Rtype/include/systems/InputsToGameEvents.hpp
  Rtype/include/systems/MonstersAutoMotion.hpp
  Rtype/include/systems/PlayerAnimation.hpp
  Rtype/include/systems/PlayerMotion.hpp
  Rtype/include/systems/PlayerShoot.hpp
  Rtype/include/systems/Start.hpp
  Rtype/source/main.cpp
  Rtype/source/systems/BackgroundMotion.cpp
  Rtype/source/systems/ClearBullets.cpp
  Rtype/source/systems/InputsToGameEvents.cpp
  Rtype/source/systems/MonstersAutoMotion.cpp
  Rtype/source/systems/PlayerAnimation.cpp
  Rtype/source/systems/PlayerMotion.cpp
  Rtype/source/systems/PlayerShoot.cpp
  Rtype/source/systems/Start.cpp
  include/GEngine/libdev/components/driver/output/Animation.hpp
  include/GEngine/libdev/systems/driver/output/Animate.hpp
  source/GEngine/interface/network/systems/Snapshot.cpp
  source/GEngine/libdev/systems/MainLoop.cpp
  source/GEngine/libdev/systems/driver/output/Animate.cpp
Labels: enhancement

#23 Windows/MacOS Fixes
  .vscode/launch.json
  CMakeLists.txt
  Rtype/CMakeLists.txt
  Rtype/source/main.cpp
  include/GEngine/interface/components/RemoteDriver.hpp
  include/GEngine/interface/network/Networked.hpp
  include/GEngine/libdev/components/driver/output/RaylibTypes.hpp
  include/GEngine/libdev/components/driver/output/Shape.hpp
  include/GEngine/libdev/components/driver/output/Sprite.hpp
  include/GEngine/libdev/components/driver/output/Text.hpp
  include/GEngine/libdev/deprecated/Color.hpp
  include/GEngine/libdev/systems/driver/input/KeyboardCatcher.hpp
  include/GEngine/libdev/systems/driver/input/MouseCatcher.hpp
  include/GEngine/libdev/systems/driver/output/Draw.hpp
  include/GEngine/libdev/systems/driver/output/FontManager.hpp
  include/GEngine/libdev/systems/driver/output/RenderWindow.hpp
  include/GEngine/libdev/systems/driver/output/SoundManager.hpp
  include/GEngine/libdev/systems/driver/output/TextureManager.hpp
  include/GEngine/libdev/systems/events/driver/input/Mouse.hpp
  include/GEngine/net/events/socket_event.hpp
  include/GEngine/net/net_address.hpp
  include/GEngine/net/net_common.hpp
  include/GEngine/net/net_socket.hpp
  include/module/raylib_safe.h
  source/GEngine/interface/components/RemoteDriver.cpp
  source/GEngine/net/events/net_socket_event.cpp
  source/GEngine/net/net.cpp
  source/GEngine/net/net_address.cpp
  source/GEngine/net/net_socket.cpp
Labels: bug, enhancement

#40 Fix/arcod mac1 : Black screens
  .vscode/launch.json
  Rtype/build/.gitkeep
  Rtype/source/systems/PlanesWave.cpp
  build/.gitkeep
  include/GEngine/interface/network/systems/ClientEventPublisher.inl
  include/GEngine/net/cl_net_client.hpp
Labels: enhancement

#43 Feat/net tcp queues
  include/GEngine/net/cl_net_client.hpp
  include/GEngine/net/msg.hpp
  include/GEngine/net/net_channel.hpp
  include/GEngine/net/net_client.hpp
  include/GEngine/net/net_queue.hpp
  include/GEngine/net/net_queue_heap.hpp
  include/GEngine/net/net_socket.hpp
  include/GEngine/net/net_tcp.hpp
  include/GEngine/net/structs/msg_udp_structs.hpp
  source/GEngine/net/cl_net_client.cpp
  source/GEngine/net/msg/msg_tcp.cpp
  source/GEngine/net/net_client.cpp
  source/GEngine/net/net_socket.cpp
  source/GEngine/net/net_tcp.cpp
Labels: enhancement, network

#46 Feat/net-compression : Compression for messages
  .gitignore
  include/GEngine/interface/network/systems/ClientEventPublisher.inl
  include/GEngine/interface/network/systems/ServerEventReceiver.inl
  include/GEngine/net/msg.hpp
  include/GEngine/net/net_huffman.hpp
  include/GEngine/net/net_queue.hpp
  include/GEngine/net/structs/msg_all_structs.hpp
  source/GEngine/interface/network/systems/Snapshot.cpp
  source/GEngine/interface/network/systems/Updater.cpp
  source/GEngine/net/msg/msg.cpp
  source/GEngine/net/msg/msg_tcp.cpp
  source/GEngine/net/msg/msg_udp.cpp
  source/GEngine/net/net_channel.cpp
  source/GEngine/net/net_huffman.cpp
Labels: enhancement, network

#52 feat motion: acceleration
  include/GEngine/libdev/Components.hpp
  include/GEngine/libdev/Systems.hpp
  include/GEngine/libdev/components/Accelerations.hpp
  include/GEngine/libdev/systems/Motions.hpp
  source/GEngine/libdev/systems/Motions.cpp
Labels: enhancement
