Repository YGNI-RType/GEngine, pull requests merged in 2024-11, with the labels that each got.

#55 Camera, RayHit, LoadModels in runtime
  examples/POC_3D/CMakeLists.txt
  examples/POC_3D/assets/models/.gitignore
  examples/POC_3D/include/components/Player.hpp
  examples/POC_3D/include/events/ChangeCameraMode.hpp
  examples/POC_3D/include/events/ChangePlayerModelEvent.hpp
  examples/POC_3D/include/events/GuessEvent.hpp
  examples/POC_3D/include/events/Sprint.hpp
  examples/POC_3D/include/systems/ChangePlayerModel.hpp
  examples/POC_3D/include/systems/Guess.hpp
  examples/POC_3D/include/systems/Init.hpp
  examples/POC_3D/include/systems/InputsToGameEvents.hpp
  examples/POC_3D/include/systems/PlayerMotion.hpp
  examples/POC_3D/run.sh
  examples/POC_3D/source/components.cpp
  examples/POC_3D/source/main.cpp
  examples/POC_3D/source/systems.cpp
  examples/POC_3D/source/systems/ChangePlayerModel.cpp
  examples/POC_3D/source/systems/Guess.cpp
  examples/POC_3D/source/systems/InputsToGameEvents.cpp
  examples/POC_3D/source/systems/PlayerMotion.cpp
  examples/POC_3D/source/systems/Start.cpp
  include/GEngine/libdev/systems/driver/output/Draw.hpp
  include/GEngine/net/net_string.hpp
  source/GEngine/libdev/systems/driver/output/Draw.cpp
  source/GEngine/libdev/systems/driver/output/ModelManager.cpp
Labels: enhancement

#60 Feat/default constructor
  cmake/automate-vcpkg.cmake
  include/GEngine/libdev/components/HitBoxs.hpp
  include/GEngine/libdev/components/Transforms.hpp
  include/GEngine/libdev/components/Velocities.hpp
  include/GEngine/libdev/components/driver/output/Animation.hpp
  include/GEngine/libdev/components/driver/output/Model.hpp
  include/GEngine/libdev/components/driver/output/RaylibTypes.hpp
  include/GEngine/libdev/components/driver/output/Shape3D.hpp
  include/GEngine/libdev/components/driver/output/Sprite.hpp
  install/cmake/automate-vcpkg-gengine.cmake
  install/cmake/compilers/Apple/armv8.cmake
  install/cmake/compilers/Apple/x64.cmake
  install/cmake/compilers/GNU/armv7.cmake
  install/cmake/compilers/GNU/armv8.cmake
  install/cmake/compilers/GNU/x86.cmake
  install/cmake/compilers/Windows/armv7.cmake
  install/cmake/compilers/Windows/armv8.cmake
  install/cmake/compilers/Windows/x86.cmake
  install/cmake/define-compilers.cmake
  install/overlay-ports/gengine/portfile.cmake
  install/overlay-ports/gengine/vcpkg.json
Labels: enhancement

#66 Network: Windows Fixes + CLI Commands
  include/GEngine/cvar/cvar.hpp
  include/GEngine/interface/network/Replay.hpp
  include/GEngine/interface/network/systems/CommandManager.hpp
  include/GEngine/interface/network/systems/NetworkWatcher.hpp
  include/GEngine/libdev/systems/CLI.hpp
  include/GEngine/libdev/systems/driver/output/Animate.hpp
  include/GEngine/net/cl_net_client.hpp
  include/GEngine/net/events/socket_event.hpp
  include/GEngine/net/msg.hpp
  include/GEngine/net/msg_error.hpp
  include/GEngine/net/net.hpp
  include/GEngine/net/net_address.hpp
  include/GEngine/net/net_channel.hpp
  include/GEngine/net/net_client.hpp
  include/GEngine/net/net_client_voip.hpp
  include/GEngine/net/net_common.hpp
  include/GEngine/net/net_event.hpp
  include/GEngine/net/net_exception.hpp
  include/GEngine/net/net_huffman.hpp
  include/GEngine/net/net_queue.hpp
  include/GEngine/net/net_queue_heap.hpp
  include/GEngine/net/net_record.hpp
  include/GEngine/net/net_server.hpp
  include/GEngine/net/net_socket.hpp
  include/GEngine/net/net_socket_error.hpp
  include/GEngine/net/net_string.hpp
  include/GEngine/net/net_utils.hpp
  include/GEngine/net/net_wait.hpp
  include/GEngine/net/structs/msg_tcp_structs.hpp
  include/GEngine/net/unused/net_ftp.hpp
  include/GEngine/net/unused/net_tcp.hpp
  include/GEngine/time/time.hpp
  include/GEngine/utils/libapi.hpp
  source/GEngine/cvar/cvar.cpp
  source/GEngine/cvar/net.cpp
  source/GEngine/interface/network/systems/ClientServer.cpp
  source/GEngine/interface/network/systems/CommandManager.cpp
  source/GEngine/interface/network/systems/NetworkWatcher.cpp
  source/GEngine/interface/network/systems/RecordManager.cpp
  source/GEngine/interface/network/systems/Snapshot.cpp
  source/GEngine/libdev/systems/CLI.cpp
  source/GEngine/net/cl_net_client.cpp
  source/GEngine/net/events/net_socket_event.cpp
  source/GEngine/net/net.cpp
  source/GEngine/net/net_address.cpp
  source/GEngine/net/net_channel.cpp
  source/GEngine/net/net_client.cpp
  source/GEngine/net/net_event.cpp
  source/GEngine/net/net_huffman.cpp
  source/GEngine/net/net_record.cpp
  source/GEngine/net/net_server.cpp
  source/GEngine/net/net_socket.cpp
  source/GEngine/net/net_tcp.cpp
  source/GEngine/net/net_wait.cpp
Labels: bug, enhancement, network

#71 Fix/cmake windows
  CMakeLists.txt
Labels: bug

#70 Fix/dev windows: Reset / Crash on End / Filesystem using \\ instead of /
  include/ecs/system/IsSystem.hpp
  source/GEngine/libdev/systems/driver/output/TextureManager.cpp
  source/GEngine/net/net_client.cpp
  source/GEngine/net/net_socket.cpp
  source/GEngine/net/net_wait.cpp
Labels: bug

#76 Fix/resize macos
  CMakeLists.txt
  include/GEngine/libdev/systems/driver/output/AudioManager.hpp
  include/GEngine/libdev/systems/driver/output/RenderWindow.hpp
  source/GEngine/libdev/systems/driver/output/RenderWindow.cpp
Labels: bug

#82 update: install folder
  install/overlay-ports/gengine/portfile.cmake
  install/overlay-ports/gengine/vcpkg.json
Labels: enhancement

#84 Fix/network: Windows / Linux Network thread bugs compilation
  blender/export.py
  include/GEngine/interface/network/Replay.hpp
  include/GEngine/interface/network/events/Record.hpp
  include/GEngine/interface/network/systems/RecordManager.hpp
  include/GEngine/interface/network/systems/ServerEventReceiver.inl
  include/GEngine/interface/network/systems/VoIPManager.hpp
  include/GEngine/libdev/systems/driver/input/VoIPAudioCatcher.hpp
  include/GEngine/libdev/systems/driver/output/VoIPAudio.hpp
  include/GEngine/net/cl_net_client.hpp
  include/GEngine/net/msg.hpp
  include/GEngine/net/net_client.hpp
  include/GEngine/net/net_record.hpp
  source/GEngine/interface/network/systems/CommandManager.cpp
  source/GEngine/interface/network/systems/RecordManager.cpp
  source/GEngine/interface/network/systems/Snapshot.cpp
  source/GEngine/interface/network/systems/Updater.cpp
  source/GEngine/interface/network/systems/VoIPManager.cpp
  source/GEngine/libdev/systems/driver/input/VoIPAudioCatcher.cpp
  source/GEngine/libdev/systems/driver/output/AudioManager.cpp
  source/GEngine/libdev/systems/driver/output/VoIPAudio.cpp
  source/GEngine/net/cl_net_client.cpp
  source/GEngine/net/msg/msg.cpp
  source/GEngine/net/net_channel.cpp
  source/GEngine/net/net_huffman.cpp
  source/GEngine/net/net_record.cpp
  source/GEngine/net/net_server.cpp
  source/GEngine/net/net_socket.cpp
  source/GEngine/net/net_wait.cpp
Labels: bug, network

#85 Feat/multicast: Multicast instead of Broadcast for IPv4
  include/GEngine/net/events/socket_event.hpp
  include/GEngine/net/net.hpp
  include/GEngine/net/net_address.hpp
  include/GEngine/net/net_socket.hpp
  include/GEngine/net/structs/msg_udp_structs.hpp
  source/GEngine/net/cl_net_client.cpp
  source/GEngine/net/net.cpp
  source/GEngine/net/net_address.cpp
  source/GEngine/net/net_server.cpp
  source/GEngine/net/net_socket.cpp
Labels: enhancement, network

#88 Fix CLI/Network: Detached thread made trouble
  include/GEngine/libdev/Systems.hpp
  include/GEngine/libdev/systems/CLI.hpp
  include/GEngine/net/net.hpp
  include/GEngine/net/net_event.hpp
  include/GEngine/net/net_socket_system.hpp
  include/GEngine/net/net_wait.hpp
  source/GEngine/libdev/systems/CLI.cpp
  source/GEngine/libdev/systems/driver/output/VoIPAudio.cpp
  source/GEngine/net/cl_net_client.cpp
  source/GEngine/net/events/net_socket_event.cpp
  source/GEngine/net/net.cpp
  source/GEngine/net/net_event.cpp
  source/GEngine/net/net_socket.cpp
  source/GEngine/net/net_socket_system.cpp
  source/GEngine/net/net_wait.cpp
Labels: bug

#93 v0.6.3
  include/GEngine/libdev/components/driver/output/Sound.hpp
  source/GEngine/libdev/systems/driver/output/AudioManager.cpp
Labels: release
